name: CI

on: [push, pull_request]

jobs:
  fmt:
      name: Rustfmt
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo install cargo-binstall
      - run: cargo binstall leptosfmt
      - uses: Swatinem/rust-cache@v2
      - name: Enforce leptos formatting
        run: leptosfmt --check .
      - name: Enforce rust formatting
        run: cargo fmt --check

  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-audit
        run: cargo binstall cargo-audit

      - name: Security check
        run: cargo audit

      - name: Dependency policy check
        run: cargo deny check

      - name: Test coverage gate
        run: cargo tarpaulin --fail-under 80

      - name: Build using cargo chef
        run: |
          cargo chef prepare --recipe-path recipe.json
          cargo chef cook --recipe-path recipe.json
          cargo build --release
